// Generated by CoffeeScript 1.8.0
(function() {
  var Collection = Backbone.Collection.extend({url: '/js/woodworkers.json'});
  var c = new Collection();
  c.fetch();
  c.on('sync', function() {
    new Marionette.Carpenter.Controller({
      title: 'Woodworkers',
      'static': true,
      region: new Backbone.Marionette.Region({
        el: '#woodworkers-table-region'
      }),
      columns: [
        { attribute: 'first_name' },
        { attribute: 'last_name' }
      ],
      collection: c
    });
  });

}).call(this);

//# sourceMappingURL=woodworkers-table.js.map
